/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutorRouteImport } from './routes/autor'
import { Route as FrasesRouteImport } from './routes/frases'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as LivroRouteImport } from './routes/livro'
import { Route as PersonagensRouteImport } from './routes/personagens'
import { Route as PlanetasRouteImport } from './routes/planetas'
import { Route as PoentesRouteImport } from './routes/poentes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorRoute = AutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => rootRouteImport,
} as any)
const FrasesRoute = FrasesRouteImport.update({
  id: '/frases',
  path: '/frases',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroRoute = LivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensRoute = PersonagensRouteImport.update({
  id: '/personagens',
  path: '/personagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetasRoute = PlanetasRouteImport.update({
  id: '/planetas',
  path: '/planetas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoentesRoute = PoentesRouteImport.update({
  id: '/poentes',
  path: '/poentes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/frases': typeof FrasesRoute
  '/galeria': typeof GaleriaRoute
  '/jornada': typeof JornadaRoute
  '/livro': typeof LivroRoute
  '/personagens': typeof PersonagensRoute
  '/planetas': typeof PlanetasRoute
  '/poentes': typeof PoentesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/frases': typeof FrasesRoute
  '/galeria': typeof GaleriaRoute
  '/jornada': typeof JornadaRoute
  '/livro': typeof LivroRoute
  '/personagens': typeof PersonagensRoute
  '/planetas': typeof PlanetasRoute
  '/poentes': typeof PoentesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/frases': typeof FrasesRoute
  '/galeria': typeof GaleriaRoute
  '/jornada': typeof JornadaRoute
  '/livro': typeof LivroRoute
  '/personagens': typeof PersonagensRoute
  '/planetas': typeof PlanetasRoute
  '/poentes': typeof PoentesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autor'
    | '/frases'
    | '/galeria'
    | '/jornada'
    | '/livro'
    | '/personagens'
    | '/planetas'
    | '/poentes'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autor'
    | '/frases'
    | '/galeria'
    | '/jornada'
    | '/livro'
    | '/personagens'
    | '/planetas'
    | '/poentes'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/autor'
    | '/frases'
    | '/galeria'
    | '/jornada'
    | '/livro'
    | '/personagens'
    | '/planetas'
    | '/poentes'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorRoute: typeof AutorRoute
  FrasesRoute: typeof FrasesRoute
  GaleriaRoute: typeof GaleriaRoute
  JornadaRoute: typeof JornadaRoute
  LivroRoute: typeof LivroRoute
  PersonagensRoute: typeof PersonagensRoute
  PlanetasRoute: typeof PlanetasRoute
  PoentesRoute: typeof PoentesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor': {
      id: '/autor'
      path: '/autor'
      fullPath: '/autor'
      preLoaderRoute: typeof AutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frases': {
      id: '/frases'
      path: '/frases'
      fullPath: '/frases'
      preLoaderRoute: typeof FrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro': {
      id: '/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof LivroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens': {
      id: '/personagens'
      path: '/personagens'
      fullPath: '/personagens'
      preLoaderRoute: typeof PersonagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planetas': {
      id: '/planetas'
      path: '/planetas'
      fullPath: '/planetas'
      preLoaderRoute: typeof PlanetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poentes': {
      id: '/poentes'
      path: '/poentes'
      fullPath: '/poentes'
      preLoaderRoute: typeof PoentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorRoute: AutorRoute,
  FrasesRoute: FrasesRoute,
  GaleriaRoute: GaleriaRoute,
  JornadaRoute: JornadaRoute,
  LivroRoute: LivroRoute,
  PersonagensRoute: PersonagensRoute,
  PlanetasRoute: PlanetasRoute,
  PoentesRoute: PoentesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
